### ISSUE TITLE
very nice !! just want to know how to print in arabic letters?

### ISSUE THREAD

**Issue by lilian131** [knyga/node-termal-printer-template#1]

**Comment by knyga** [comment]
Sorry for the long reply. Missed the message.
Repository is based on the https://github.com/knyga/node-thermal-printer
At the initialization step you can set characterSet property. For example.
```
characterSet: PrinterCharSets.EPSON.ARABIA,  
// Buffer.from([0x1b, 0x52, 0x11])
```
And it should work. See the full list of charsets (epson and start have different chartset codes):
https://github.com/knyga/node-thermal-printer/blob/master/lib/types/epson-config.js
https://github.com/knyga/node-thermal-printer/blob/master/lib/types/star-config.js
