### ISSUE TITLE
html with external style

### ISSUE THREAD

**Issue by iCloudsPWASaaS** [knyga/node-termal-printer-template#2]
Hi,

I want to send html using external style, do you think this can be able to print.

**Comment by knyga** [comment]
@WebScaffolder Hi!
It looks like the task for inline-css: https://www.npmjs.com/package/inline-css

**Comment by nipoonp** [comment]
Hi buddy,

I tried both inline styling and using a separate styling css tag. However, it both dont seem to work. 

Even tried to the inline-css library.

Any suggestions on what I could try?
