### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by MarquesCoding** [knyga/node-termal-printer-template#3]
Hi,

So I have a list of members in an Array and want to print that persons name. I itterate through the array and run 'execute(printer, template);' but for some reason it runs through the array and keeps on printing the last one over and over and over...

any ideas?

Thanks

**Comment by knyga** [comment]
@MarquesCoding It looks like closure issue :)
https://stackoverflow.com/questions/750486/javascript-closure-inside-loops-simple-practical-example

Could you share the code, please?
